name: Quality Control

on: [ push ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: cmake -B build && cmake --build build

      - name: Install lcov and genhtml
        run: sudo apt-get install -y lcov

      - name: Run tests
        run: cd build && make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3